site_name: Módulo IAW
theme:
  name: material

nav:
  - Inicio: index.md
  - Tema 1. Introducción a HTTP:
      - Teoría CURL: Teoria CURL.md
      - Practica 1. CURL y POSTMAN: Práctica 1.md
      -  Practica 2. Introduccion a APACHE e instalacion : 2 Teoría-Práctica-Guiada.md

  - Tema 2. Lenguajes de entorno sevidor PHP:
      - Práctica 3. Sintaxis, ejecución y estructuras de datos.: 3 primera_practica_PHP.md
      - Práctica 4. Métodos avanzados. Peticiones fetch y HTML: practica4_php.md
      
  - Tema 3. Acceso a bases de datos desde lenguajes de entorno servidor y uso de frameworks PHP:
      - Practica 5. Setters y Getters. Conexion BBDD y manejo de peticiones en servidor: 5-Práctica. Conexiones_bd.md
      -  Practica 6. Borrar y cambiar registros de la BD. Uso básico de cookies.: 6-Practica.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
